name: mealie_api
description: Dart SDK for Mealie Recipe Management API
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.5.1

dependencies:
  dio: ^5.4.2+1
  json_annotation: ^4.9.0
  built_value: ^8.9.2
  built_collection: ^5.1.1

dev_dependencies:
  build_runner: ^2.4.9
  built_value_generator: ^8.9.2
  json_serializable: ^6.7.1
  test: ^1.21.0

flutter:
  uses-material-design: true